### ISSUE TITLE
Leading spaces should not be formatted

### ISSUE THREAD

**Issue by adhocish** [tiffon/sublime-to-done#12]
![capture](https://cloud.githubusercontent.com/assets/3294357/9498803/cd8e89ee-4be9-11e5-802a-16ddc1786d6c.PNG)

**Comment by tiffon** [comment]
Thanks for filing. Will look into it.

Just curious, is there a reason you're not using hard-tabs?

**Comment by adhocish** [comment]
Hard tabs are a huge pain to sync across multiple machines (especially ones you don't control). Spaces are universal.
